# This workflow will build a docker container, publish it to Google Container Registry.
#
# To configure this workflow:
#
# Set up secrets in your workspace: GKE_PROJECT with the name of the project and GKE_SA_KEY with the Base64 encoded JSON service account key (https://github.com/GoogleCloudPlatform/github-actions/tree/docs/service-account-key/setup-gcloud#inputs).
#
# For more support on how to run the workflow, please visit https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/gke

name: Build and Publish to Container Registry

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  JAVA_VERSION: '17'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'

      - name: Read gradle environment
        run: |
          PROJECT_NAME=$(./gradlew -q project_name | tail -n 1)
          PROJECT_VERSION=$(./gradlew -q project_version | tail -n 1)
          echo PROJECT_VERSION=$PROJECT_VERSION >> $GITHUB_ENV
          echo PROJECT_NAME=$PROJECT_NAME >> $GITHUB_ENV
          echo "env.PROJECT_VERSION: $PROJECT_VERSION"
          echo "env.PROJECT_NAME: $PROJECT_NAME"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: clean bootJar

      - name: Setup auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0

      - name: Configure docker to use Google Container Registry
        run: gcloud auth configure-docker

      - name: Build
        run: |-
          docker build \
            --tag "eu.gcr.io/$PROJECT_ID/$PROJECT_NAME:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      - name: Publish
        run: |-
          docker push eu.gcr.io/$PROJECT_ID/$PROJECT_NAME:$GITHUB_SHA
          docker tag \
            "eu.gcr.io/$PROJECT_ID/$PROJECT_NAME:$GITHUB_SHA" \
            "eu.gcr.io/$PROJECT_ID/$PROJECT_NAME:${PROJECT_VERSION}"
          docker push "eu.gcr.io/$PROJECT_ID/$PROJECT_NAME:${PROJECT_VERSION}"
